modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "rks_airdrops"
version = "${version}"
displayName = "Simply Airdrops"
logoFile = "logo.png"
description = '''
Adds custom airdrop crates with animated storage for Simply Airdrops.
'''

[[dependencies.rks_airdrops]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rks_airdrops]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
